// Code generated by ent, DO NOT EDIT.

package endpointdata

import (
	"servicediscoverer/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// DataName applies equality check predicate on the "dataName" field. It's identical to DataNameEQ.
func DataName(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDataName), v))
	})
}

// Discription applies equality check predicate on the "discription" field. It's identical to DiscriptionEQ.
func Discription(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDiscription), v))
	})
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPath), v))
	})
}

// DataNameEQ applies the EQ predicate on the "dataName" field.
func DataNameEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDataName), v))
	})
}

// DataNameNEQ applies the NEQ predicate on the "dataName" field.
func DataNameNEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDataName), v))
	})
}

// DataNameIn applies the In predicate on the "dataName" field.
func DataNameIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDataName), v...))
	})
}

// DataNameNotIn applies the NotIn predicate on the "dataName" field.
func DataNameNotIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDataName), v...))
	})
}

// DataNameGT applies the GT predicate on the "dataName" field.
func DataNameGT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDataName), v))
	})
}

// DataNameGTE applies the GTE predicate on the "dataName" field.
func DataNameGTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDataName), v))
	})
}

// DataNameLT applies the LT predicate on the "dataName" field.
func DataNameLT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDataName), v))
	})
}

// DataNameLTE applies the LTE predicate on the "dataName" field.
func DataNameLTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDataName), v))
	})
}

// DataNameContains applies the Contains predicate on the "dataName" field.
func DataNameContains(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDataName), v))
	})
}

// DataNameHasPrefix applies the HasPrefix predicate on the "dataName" field.
func DataNameHasPrefix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDataName), v))
	})
}

// DataNameHasSuffix applies the HasSuffix predicate on the "dataName" field.
func DataNameHasSuffix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDataName), v))
	})
}

// DataNameEqualFold applies the EqualFold predicate on the "dataName" field.
func DataNameEqualFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDataName), v))
	})
}

// DataNameContainsFold applies the ContainsFold predicate on the "dataName" field.
func DataNameContainsFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDataName), v))
	})
}

// DiscriptionEQ applies the EQ predicate on the "discription" field.
func DiscriptionEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDiscription), v))
	})
}

// DiscriptionNEQ applies the NEQ predicate on the "discription" field.
func DiscriptionNEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDiscription), v))
	})
}

// DiscriptionIn applies the In predicate on the "discription" field.
func DiscriptionIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDiscription), v...))
	})
}

// DiscriptionNotIn applies the NotIn predicate on the "discription" field.
func DiscriptionNotIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDiscription), v...))
	})
}

// DiscriptionGT applies the GT predicate on the "discription" field.
func DiscriptionGT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDiscription), v))
	})
}

// DiscriptionGTE applies the GTE predicate on the "discription" field.
func DiscriptionGTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDiscription), v))
	})
}

// DiscriptionLT applies the LT predicate on the "discription" field.
func DiscriptionLT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDiscription), v))
	})
}

// DiscriptionLTE applies the LTE predicate on the "discription" field.
func DiscriptionLTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDiscription), v))
	})
}

// DiscriptionContains applies the Contains predicate on the "discription" field.
func DiscriptionContains(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDiscription), v))
	})
}

// DiscriptionHasPrefix applies the HasPrefix predicate on the "discription" field.
func DiscriptionHasPrefix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDiscription), v))
	})
}

// DiscriptionHasSuffix applies the HasSuffix predicate on the "discription" field.
func DiscriptionHasSuffix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDiscription), v))
	})
}

// DiscriptionEqualFold applies the EqualFold predicate on the "discription" field.
func DiscriptionEqualFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDiscription), v))
	})
}

// DiscriptionContainsFold applies the ContainsFold predicate on the "discription" field.
func DiscriptionContainsFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDiscription), v))
	})
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldType), v))
	})
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldType), v))
	})
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldType), v...))
	})
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldType), v...))
	})
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldType), v))
	})
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldType), v))
	})
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldType), v))
	})
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldType), v))
	})
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldType), v))
	})
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldType), v))
	})
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldType), v))
	})
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldType), v))
	})
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldType), v))
	})
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPath), v))
	})
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPath), v))
	})
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPath), v...))
	})
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.EndpointData {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPath), v...))
	})
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPath), v))
	})
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPath), v))
	})
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPath), v))
	})
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPath), v))
	})
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPath), v))
	})
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPath), v))
	})
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPath), v))
	})
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPath), v))
	})
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPath), v))
	})
}

// HasEndpointRequired applies the HasEdge predicate on the "endpointRequired" edge.
func HasEndpointRequired() predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EndpointRequiredTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EndpointRequiredTable, EndpointRequiredColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEndpointRequiredWith applies the HasEdge predicate on the "endpointRequired" edge with a given conditions (other predicates).
func HasEndpointRequiredWith(preds ...predicate.ProviderEndpoint) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EndpointRequiredInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EndpointRequiredTable, EndpointRequiredColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEndpointProvided applies the HasEdge predicate on the "endpointProvided" edge.
func HasEndpointProvided() predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EndpointProvidedTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EndpointProvidedTable, EndpointProvidedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEndpointProvidedWith applies the HasEdge predicate on the "endpointProvided" edge with a given conditions (other predicates).
func HasEndpointProvidedWith(preds ...predicate.ProviderEndpoint) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EndpointProvidedInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EndpointProvidedTable, EndpointProvidedColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EndpointData) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EndpointData) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EndpointData) predicate.EndpointData {
	return predicate.EndpointData(func(s *sql.Selector) {
		p(s.Not())
	})
}
