// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"github.com/go-faster/jx"
)

type CreateEndpointDataReq struct {
	DataName         string `json:"dataName"`
	Description      string `json:"description"`
	Type             string `json:"type"`
	EndpointRequired OptInt `json:"endpoint_required"`
	EndpointProvided OptInt `json:"endpoint_provided"`
}

// GetDataName returns the value of DataName.
func (s *CreateEndpointDataReq) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *CreateEndpointDataReq) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *CreateEndpointDataReq) GetType() string {
	return s.Type
}

// GetEndpointRequired returns the value of EndpointRequired.
func (s *CreateEndpointDataReq) GetEndpointRequired() OptInt {
	return s.EndpointRequired
}

// GetEndpointProvided returns the value of EndpointProvided.
func (s *CreateEndpointDataReq) GetEndpointProvided() OptInt {
	return s.EndpointProvided
}

// SetDataName sets the value of DataName.
func (s *CreateEndpointDataReq) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *CreateEndpointDataReq) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *CreateEndpointDataReq) SetType(val string) {
	s.Type = val
}

// SetEndpointRequired sets the value of EndpointRequired.
func (s *CreateEndpointDataReq) SetEndpointRequired(val OptInt) {
	s.EndpointRequired = val
}

// SetEndpointProvided sets the value of EndpointProvided.
func (s *CreateEndpointDataReq) SetEndpointProvided(val OptInt) {
	s.EndpointProvided = val
}

type CreateProviderEndpointReq struct {
	Name         string `json:"name"`
	Path         string `json:"path"`
	Type         string `json:"type"`
	Description  string `json:"description"`
	RequiredData []int  `json:"required_data"`
	ProvidedData []int  `json:"provided_data"`
	Provider     OptInt `json:"provider"`
}

// GetName returns the value of Name.
func (s *CreateProviderEndpointReq) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *CreateProviderEndpointReq) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *CreateProviderEndpointReq) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *CreateProviderEndpointReq) GetDescription() string {
	return s.Description
}

// GetRequiredData returns the value of RequiredData.
func (s *CreateProviderEndpointReq) GetRequiredData() []int {
	return s.RequiredData
}

// GetProvidedData returns the value of ProvidedData.
func (s *CreateProviderEndpointReq) GetProvidedData() []int {
	return s.ProvidedData
}

// GetProvider returns the value of Provider.
func (s *CreateProviderEndpointReq) GetProvider() OptInt {
	return s.Provider
}

// SetName sets the value of Name.
func (s *CreateProviderEndpointReq) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *CreateProviderEndpointReq) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *CreateProviderEndpointReq) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *CreateProviderEndpointReq) SetDescription(val string) {
	s.Description = val
}

// SetRequiredData sets the value of RequiredData.
func (s *CreateProviderEndpointReq) SetRequiredData(val []int) {
	s.RequiredData = val
}

// SetProvidedData sets the value of ProvidedData.
func (s *CreateProviderEndpointReq) SetProvidedData(val []int) {
	s.ProvidedData = val
}

// SetProvider sets the value of Provider.
func (s *CreateProviderEndpointReq) SetProvider(val OptInt) {
	s.Provider = val
}

type CreateProviderRegisterDataReq struct {
	Name         string `json:"name"`
	Port         string `json:"port"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	LiveInterval int    `json:"liveInterval"`
	LiveTimeout  int    `json:"liveTimeout"`
	Endpoints    []int  `json:"endpoints"`
}

// GetName returns the value of Name.
func (s *CreateProviderRegisterDataReq) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *CreateProviderRegisterDataReq) GetPort() string {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *CreateProviderRegisterDataReq) GetAddress() string {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *CreateProviderRegisterDataReq) GetDescription() string {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *CreateProviderRegisterDataReq) GetLiveInterval() int {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *CreateProviderRegisterDataReq) GetLiveTimeout() int {
	return s.LiveTimeout
}

// GetEndpoints returns the value of Endpoints.
func (s *CreateProviderRegisterDataReq) GetEndpoints() []int {
	return s.Endpoints
}

// SetName sets the value of Name.
func (s *CreateProviderRegisterDataReq) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *CreateProviderRegisterDataReq) SetPort(val string) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *CreateProviderRegisterDataReq) SetAddress(val string) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *CreateProviderRegisterDataReq) SetDescription(val string) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *CreateProviderRegisterDataReq) SetLiveInterval(val int) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *CreateProviderRegisterDataReq) SetLiveTimeout(val int) {
	s.LiveTimeout = val
}

// SetEndpoints sets the value of Endpoints.
func (s *CreateProviderRegisterDataReq) SetEndpoints(val []int) {
	s.Endpoints = val
}

// DeleteEndpointDataNoContent is response for DeleteEndpointData operation.
type DeleteEndpointDataNoContent struct{}

func (*DeleteEndpointDataNoContent) deleteEndpointDataRes() {}

// DeleteProviderEndpointNoContent is response for DeleteProviderEndpoint operation.
type DeleteProviderEndpointNoContent struct{}

func (*DeleteProviderEndpointNoContent) deleteProviderEndpointRes() {}

// DeleteProviderRegisterDataNoContent is response for DeleteProviderRegisterData operation.
type DeleteProviderRegisterDataNoContent struct{}

func (*DeleteProviderRegisterDataNoContent) deleteProviderRegisterDataRes() {}

// Ref: #/components/schemas/EndpointDataCreate
type EndpointDataCreate struct {
	ID          int    `json:"id"`
	DataName    string `json:"dataName"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// GetID returns the value of ID.
func (s *EndpointDataCreate) GetID() int {
	return s.ID
}

// GetDataName returns the value of DataName.
func (s *EndpointDataCreate) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *EndpointDataCreate) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *EndpointDataCreate) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *EndpointDataCreate) SetID(val int) {
	s.ID = val
}

// SetDataName sets the value of DataName.
func (s *EndpointDataCreate) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *EndpointDataCreate) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *EndpointDataCreate) SetType(val string) {
	s.Type = val
}

func (*EndpointDataCreate) createEndpointDataRes() {}

// Ref: #/components/schemas/EndpointData_EndpointProvidedRead
type EndpointDataEndpointProvidedRead struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *EndpointDataEndpointProvidedRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *EndpointDataEndpointProvidedRead) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *EndpointDataEndpointProvidedRead) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *EndpointDataEndpointProvidedRead) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *EndpointDataEndpointProvidedRead) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *EndpointDataEndpointProvidedRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *EndpointDataEndpointProvidedRead) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *EndpointDataEndpointProvidedRead) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *EndpointDataEndpointProvidedRead) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *EndpointDataEndpointProvidedRead) SetDescription(val string) {
	s.Description = val
}

func (*EndpointDataEndpointProvidedRead) readEndpointDataEndpointProvidedRes() {}

// Ref: #/components/schemas/EndpointData_EndpointRequiredRead
type EndpointDataEndpointRequiredRead struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *EndpointDataEndpointRequiredRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *EndpointDataEndpointRequiredRead) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *EndpointDataEndpointRequiredRead) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *EndpointDataEndpointRequiredRead) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *EndpointDataEndpointRequiredRead) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *EndpointDataEndpointRequiredRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *EndpointDataEndpointRequiredRead) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *EndpointDataEndpointRequiredRead) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *EndpointDataEndpointRequiredRead) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *EndpointDataEndpointRequiredRead) SetDescription(val string) {
	s.Description = val
}

func (*EndpointDataEndpointRequiredRead) readEndpointDataEndpointRequiredRes() {}

// Ref: #/components/schemas/EndpointDataList
type EndpointDataList struct {
	ID          int    `json:"id"`
	DataName    string `json:"dataName"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// GetID returns the value of ID.
func (s *EndpointDataList) GetID() int {
	return s.ID
}

// GetDataName returns the value of DataName.
func (s *EndpointDataList) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *EndpointDataList) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *EndpointDataList) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *EndpointDataList) SetID(val int) {
	s.ID = val
}

// SetDataName sets the value of DataName.
func (s *EndpointDataList) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *EndpointDataList) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *EndpointDataList) SetType(val string) {
	s.Type = val
}

// Ref: #/components/schemas/EndpointDataRead
type EndpointDataRead struct {
	ID          int    `json:"id"`
	DataName    string `json:"dataName"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// GetID returns the value of ID.
func (s *EndpointDataRead) GetID() int {
	return s.ID
}

// GetDataName returns the value of DataName.
func (s *EndpointDataRead) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *EndpointDataRead) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *EndpointDataRead) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *EndpointDataRead) SetID(val int) {
	s.ID = val
}

// SetDataName sets the value of DataName.
func (s *EndpointDataRead) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *EndpointDataRead) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *EndpointDataRead) SetType(val string) {
	s.Type = val
}

func (*EndpointDataRead) readEndpointDataRes() {}

// Ref: #/components/schemas/EndpointDataUpdate
type EndpointDataUpdate struct {
	ID          int    `json:"id"`
	DataName    string `json:"dataName"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// GetID returns the value of ID.
func (s *EndpointDataUpdate) GetID() int {
	return s.ID
}

// GetDataName returns the value of DataName.
func (s *EndpointDataUpdate) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *EndpointDataUpdate) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *EndpointDataUpdate) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *EndpointDataUpdate) SetID(val int) {
	s.ID = val
}

// SetDataName sets the value of DataName.
func (s *EndpointDataUpdate) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *EndpointDataUpdate) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *EndpointDataUpdate) SetType(val string) {
	s.Type = val
}

func (*EndpointDataUpdate) updateEndpointDataRes() {}

type ListEndpointDataOKApplicationJSON []EndpointDataList

func (ListEndpointDataOKApplicationJSON) listEndpointDataRes() {}

type ListProviderEndpointOKApplicationJSON []ProviderEndpointList

func (ListProviderEndpointOKApplicationJSON) listProviderEndpointRes() {}

type ListProviderEndpointProvidedDataOKApplicationJSON []ProviderEndpointProvidedDataList

func (ListProviderEndpointProvidedDataOKApplicationJSON) listProviderEndpointProvidedDataRes() {}

type ListProviderEndpointRequiredDataOKApplicationJSON []ProviderEndpointRequiredDataList

func (ListProviderEndpointRequiredDataOKApplicationJSON) listProviderEndpointRequiredDataRes() {}

type ListProviderRegisterDataEndpointsOKApplicationJSON []ProviderRegisterDataEndpointsList

func (ListProviderRegisterDataEndpointsOKApplicationJSON) listProviderRegisterDataEndpointsRes() {}

type ListProviderRegisterDataOKApplicationJSON []ProviderRegisterDataList

func (ListProviderRegisterDataOKApplicationJSON) listProviderRegisterDataRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ProviderEndpointCreate
type ProviderEndpointCreate struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointCreate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderEndpointCreate) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *ProviderEndpointCreate) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *ProviderEndpointCreate) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointCreate) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *ProviderEndpointCreate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderEndpointCreate) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *ProviderEndpointCreate) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *ProviderEndpointCreate) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointCreate) SetDescription(val string) {
	s.Description = val
}

func (*ProviderEndpointCreate) createProviderEndpointRes() {}

// Ref: #/components/schemas/ProviderEndpointList
type ProviderEndpointList struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointList) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderEndpointList) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *ProviderEndpointList) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *ProviderEndpointList) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointList) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *ProviderEndpointList) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderEndpointList) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *ProviderEndpointList) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *ProviderEndpointList) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointList) SetDescription(val string) {
	s.Description = val
}

// Ref: #/components/schemas/ProviderEndpoint_ProvidedDataList
type ProviderEndpointProvidedDataList struct {
	ID          int    `json:"id"`
	DataName    string `json:"dataName"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointProvidedDataList) GetID() int {
	return s.ID
}

// GetDataName returns the value of DataName.
func (s *ProviderEndpointProvidedDataList) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointProvidedDataList) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *ProviderEndpointProvidedDataList) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *ProviderEndpointProvidedDataList) SetID(val int) {
	s.ID = val
}

// SetDataName sets the value of DataName.
func (s *ProviderEndpointProvidedDataList) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointProvidedDataList) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *ProviderEndpointProvidedDataList) SetType(val string) {
	s.Type = val
}

// Ref: #/components/schemas/ProviderEndpoint_ProviderRead
type ProviderEndpointProviderRead struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Port         string `json:"port"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	LiveInterval int    `json:"liveInterval"`
	LiveTimeout  int    `json:"liveTimeout"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointProviderRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderEndpointProviderRead) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *ProviderEndpointProviderRead) GetPort() string {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *ProviderEndpointProviderRead) GetAddress() string {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointProviderRead) GetDescription() string {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *ProviderEndpointProviderRead) GetLiveInterval() int {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *ProviderEndpointProviderRead) GetLiveTimeout() int {
	return s.LiveTimeout
}

// SetID sets the value of ID.
func (s *ProviderEndpointProviderRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderEndpointProviderRead) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *ProviderEndpointProviderRead) SetPort(val string) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *ProviderEndpointProviderRead) SetAddress(val string) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointProviderRead) SetDescription(val string) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *ProviderEndpointProviderRead) SetLiveInterval(val int) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *ProviderEndpointProviderRead) SetLiveTimeout(val int) {
	s.LiveTimeout = val
}

func (*ProviderEndpointProviderRead) readProviderEndpointProviderRes() {}

// Ref: #/components/schemas/ProviderEndpointRead
type ProviderEndpointRead struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderEndpointRead) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *ProviderEndpointRead) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *ProviderEndpointRead) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointRead) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *ProviderEndpointRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderEndpointRead) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *ProviderEndpointRead) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *ProviderEndpointRead) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointRead) SetDescription(val string) {
	s.Description = val
}

func (*ProviderEndpointRead) readProviderEndpointRes() {}

// Ref: #/components/schemas/ProviderEndpoint_RequiredDataList
type ProviderEndpointRequiredDataList struct {
	ID          int    `json:"id"`
	DataName    string `json:"dataName"`
	Description string `json:"description"`
	Type        string `json:"type"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointRequiredDataList) GetID() int {
	return s.ID
}

// GetDataName returns the value of DataName.
func (s *ProviderEndpointRequiredDataList) GetDataName() string {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointRequiredDataList) GetDescription() string {
	return s.Description
}

// GetType returns the value of Type.
func (s *ProviderEndpointRequiredDataList) GetType() string {
	return s.Type
}

// SetID sets the value of ID.
func (s *ProviderEndpointRequiredDataList) SetID(val int) {
	s.ID = val
}

// SetDataName sets the value of DataName.
func (s *ProviderEndpointRequiredDataList) SetDataName(val string) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointRequiredDataList) SetDescription(val string) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *ProviderEndpointRequiredDataList) SetType(val string) {
	s.Type = val
}

// Ref: #/components/schemas/ProviderEndpointUpdate
type ProviderEndpointUpdate struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *ProviderEndpointUpdate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderEndpointUpdate) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *ProviderEndpointUpdate) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *ProviderEndpointUpdate) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *ProviderEndpointUpdate) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *ProviderEndpointUpdate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderEndpointUpdate) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *ProviderEndpointUpdate) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *ProviderEndpointUpdate) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *ProviderEndpointUpdate) SetDescription(val string) {
	s.Description = val
}

func (*ProviderEndpointUpdate) updateProviderEndpointRes() {}

// Ref: #/components/schemas/ProviderRegisterDataCreate
type ProviderRegisterDataCreate struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Port         string `json:"port"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	LiveInterval int    `json:"liveInterval"`
	LiveTimeout  int    `json:"liveTimeout"`
}

// GetID returns the value of ID.
func (s *ProviderRegisterDataCreate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderRegisterDataCreate) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *ProviderRegisterDataCreate) GetPort() string {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *ProviderRegisterDataCreate) GetAddress() string {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *ProviderRegisterDataCreate) GetDescription() string {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *ProviderRegisterDataCreate) GetLiveInterval() int {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *ProviderRegisterDataCreate) GetLiveTimeout() int {
	return s.LiveTimeout
}

// SetID sets the value of ID.
func (s *ProviderRegisterDataCreate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderRegisterDataCreate) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *ProviderRegisterDataCreate) SetPort(val string) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *ProviderRegisterDataCreate) SetAddress(val string) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *ProviderRegisterDataCreate) SetDescription(val string) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *ProviderRegisterDataCreate) SetLiveInterval(val int) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *ProviderRegisterDataCreate) SetLiveTimeout(val int) {
	s.LiveTimeout = val
}

func (*ProviderRegisterDataCreate) createProviderRegisterDataRes() {}

// Ref: #/components/schemas/ProviderRegisterData_EndpointsList
type ProviderRegisterDataEndpointsList struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Path        string `json:"path"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// GetID returns the value of ID.
func (s *ProviderRegisterDataEndpointsList) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderRegisterDataEndpointsList) GetName() string {
	return s.Name
}

// GetPath returns the value of Path.
func (s *ProviderRegisterDataEndpointsList) GetPath() string {
	return s.Path
}

// GetType returns the value of Type.
func (s *ProviderRegisterDataEndpointsList) GetType() string {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *ProviderRegisterDataEndpointsList) GetDescription() string {
	return s.Description
}

// SetID sets the value of ID.
func (s *ProviderRegisterDataEndpointsList) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderRegisterDataEndpointsList) SetName(val string) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *ProviderRegisterDataEndpointsList) SetPath(val string) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *ProviderRegisterDataEndpointsList) SetType(val string) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *ProviderRegisterDataEndpointsList) SetDescription(val string) {
	s.Description = val
}

// Ref: #/components/schemas/ProviderRegisterDataList
type ProviderRegisterDataList struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Port         string `json:"port"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	LiveInterval int    `json:"liveInterval"`
	LiveTimeout  int    `json:"liveTimeout"`
}

// GetID returns the value of ID.
func (s *ProviderRegisterDataList) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderRegisterDataList) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *ProviderRegisterDataList) GetPort() string {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *ProviderRegisterDataList) GetAddress() string {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *ProviderRegisterDataList) GetDescription() string {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *ProviderRegisterDataList) GetLiveInterval() int {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *ProviderRegisterDataList) GetLiveTimeout() int {
	return s.LiveTimeout
}

// SetID sets the value of ID.
func (s *ProviderRegisterDataList) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderRegisterDataList) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *ProviderRegisterDataList) SetPort(val string) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *ProviderRegisterDataList) SetAddress(val string) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *ProviderRegisterDataList) SetDescription(val string) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *ProviderRegisterDataList) SetLiveInterval(val int) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *ProviderRegisterDataList) SetLiveTimeout(val int) {
	s.LiveTimeout = val
}

// Ref: #/components/schemas/ProviderRegisterDataRead
type ProviderRegisterDataRead struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Port         string `json:"port"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	LiveInterval int    `json:"liveInterval"`
	LiveTimeout  int    `json:"liveTimeout"`
}

// GetID returns the value of ID.
func (s *ProviderRegisterDataRead) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderRegisterDataRead) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *ProviderRegisterDataRead) GetPort() string {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *ProviderRegisterDataRead) GetAddress() string {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *ProviderRegisterDataRead) GetDescription() string {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *ProviderRegisterDataRead) GetLiveInterval() int {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *ProviderRegisterDataRead) GetLiveTimeout() int {
	return s.LiveTimeout
}

// SetID sets the value of ID.
func (s *ProviderRegisterDataRead) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderRegisterDataRead) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *ProviderRegisterDataRead) SetPort(val string) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *ProviderRegisterDataRead) SetAddress(val string) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *ProviderRegisterDataRead) SetDescription(val string) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *ProviderRegisterDataRead) SetLiveInterval(val int) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *ProviderRegisterDataRead) SetLiveTimeout(val int) {
	s.LiveTimeout = val
}

func (*ProviderRegisterDataRead) readProviderRegisterDataRes() {}

// Ref: #/components/schemas/ProviderRegisterDataUpdate
type ProviderRegisterDataUpdate struct {
	ID           int    `json:"id"`
	Name         string `json:"name"`
	Port         string `json:"port"`
	Address      string `json:"address"`
	Description  string `json:"description"`
	LiveInterval int    `json:"liveInterval"`
	LiveTimeout  int    `json:"liveTimeout"`
}

// GetID returns the value of ID.
func (s *ProviderRegisterDataUpdate) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProviderRegisterDataUpdate) GetName() string {
	return s.Name
}

// GetPort returns the value of Port.
func (s *ProviderRegisterDataUpdate) GetPort() string {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *ProviderRegisterDataUpdate) GetAddress() string {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *ProviderRegisterDataUpdate) GetDescription() string {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *ProviderRegisterDataUpdate) GetLiveInterval() int {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *ProviderRegisterDataUpdate) GetLiveTimeout() int {
	return s.LiveTimeout
}

// SetID sets the value of ID.
func (s *ProviderRegisterDataUpdate) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProviderRegisterDataUpdate) SetName(val string) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *ProviderRegisterDataUpdate) SetPort(val string) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *ProviderRegisterDataUpdate) SetAddress(val string) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *ProviderRegisterDataUpdate) SetDescription(val string) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *ProviderRegisterDataUpdate) SetLiveInterval(val int) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *ProviderRegisterDataUpdate) SetLiveTimeout(val int) {
	s.LiveTimeout = val
}

func (*ProviderRegisterDataUpdate) updateProviderRegisterDataRes() {}

type R400 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R400) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R400) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R400) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R400) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R400) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R400) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R400) createEndpointDataRes()                {}
func (*R400) createProviderEndpointRes()            {}
func (*R400) createProviderRegisterDataRes()        {}
func (*R400) deleteEndpointDataRes()                {}
func (*R400) deleteProviderEndpointRes()            {}
func (*R400) deleteProviderRegisterDataRes()        {}
func (*R400) listEndpointDataRes()                  {}
func (*R400) listProviderEndpointProvidedDataRes()  {}
func (*R400) listProviderEndpointRequiredDataRes()  {}
func (*R400) listProviderEndpointRes()              {}
func (*R400) listProviderRegisterDataEndpointsRes() {}
func (*R400) listProviderRegisterDataRes()          {}
func (*R400) readEndpointDataEndpointProvidedRes()  {}
func (*R400) readEndpointDataEndpointRequiredRes()  {}
func (*R400) readEndpointDataRes()                  {}
func (*R400) readProviderEndpointProviderRes()      {}
func (*R400) readProviderEndpointRes()              {}
func (*R400) readProviderRegisterDataRes()          {}
func (*R400) updateEndpointDataRes()                {}
func (*R400) updateProviderEndpointRes()            {}
func (*R400) updateProviderRegisterDataRes()        {}

type R404 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R404) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R404) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R404) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R404) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R404) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R404) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R404) deleteEndpointDataRes()                {}
func (*R404) deleteProviderEndpointRes()            {}
func (*R404) deleteProviderRegisterDataRes()        {}
func (*R404) listEndpointDataRes()                  {}
func (*R404) listProviderEndpointProvidedDataRes()  {}
func (*R404) listProviderEndpointRequiredDataRes()  {}
func (*R404) listProviderEndpointRes()              {}
func (*R404) listProviderRegisterDataEndpointsRes() {}
func (*R404) listProviderRegisterDataRes()          {}
func (*R404) readEndpointDataEndpointProvidedRes()  {}
func (*R404) readEndpointDataEndpointRequiredRes()  {}
func (*R404) readEndpointDataRes()                  {}
func (*R404) readProviderEndpointProviderRes()      {}
func (*R404) readProviderEndpointRes()              {}
func (*R404) readProviderRegisterDataRes()          {}
func (*R404) updateEndpointDataRes()                {}
func (*R404) updateProviderEndpointRes()            {}
func (*R404) updateProviderRegisterDataRes()        {}

type R409 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R409) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R409) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R409) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R409) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R409) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R409) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R409) createEndpointDataRes()                {}
func (*R409) createProviderEndpointRes()            {}
func (*R409) createProviderRegisterDataRes()        {}
func (*R409) deleteEndpointDataRes()                {}
func (*R409) deleteProviderEndpointRes()            {}
func (*R409) deleteProviderRegisterDataRes()        {}
func (*R409) listEndpointDataRes()                  {}
func (*R409) listProviderEndpointProvidedDataRes()  {}
func (*R409) listProviderEndpointRequiredDataRes()  {}
func (*R409) listProviderEndpointRes()              {}
func (*R409) listProviderRegisterDataEndpointsRes() {}
func (*R409) listProviderRegisterDataRes()          {}
func (*R409) readEndpointDataEndpointProvidedRes()  {}
func (*R409) readEndpointDataEndpointRequiredRes()  {}
func (*R409) readEndpointDataRes()                  {}
func (*R409) readProviderEndpointProviderRes()      {}
func (*R409) readProviderEndpointRes()              {}
func (*R409) readProviderRegisterDataRes()          {}
func (*R409) updateEndpointDataRes()                {}
func (*R409) updateProviderEndpointRes()            {}
func (*R409) updateProviderRegisterDataRes()        {}

type R500 struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
	Errors jx.Raw `json:"errors"`
}

// GetCode returns the value of Code.
func (s *R500) GetCode() int {
	return s.Code
}

// GetStatus returns the value of Status.
func (s *R500) GetStatus() string {
	return s.Status
}

// GetErrors returns the value of Errors.
func (s *R500) GetErrors() jx.Raw {
	return s.Errors
}

// SetCode sets the value of Code.
func (s *R500) SetCode(val int) {
	s.Code = val
}

// SetStatus sets the value of Status.
func (s *R500) SetStatus(val string) {
	s.Status = val
}

// SetErrors sets the value of Errors.
func (s *R500) SetErrors(val jx.Raw) {
	s.Errors = val
}

func (*R500) createEndpointDataRes()                {}
func (*R500) createProviderEndpointRes()            {}
func (*R500) createProviderRegisterDataRes()        {}
func (*R500) deleteEndpointDataRes()                {}
func (*R500) deleteProviderEndpointRes()            {}
func (*R500) deleteProviderRegisterDataRes()        {}
func (*R500) listEndpointDataRes()                  {}
func (*R500) listProviderEndpointProvidedDataRes()  {}
func (*R500) listProviderEndpointRequiredDataRes()  {}
func (*R500) listProviderEndpointRes()              {}
func (*R500) listProviderRegisterDataEndpointsRes() {}
func (*R500) listProviderRegisterDataRes()          {}
func (*R500) readEndpointDataEndpointProvidedRes()  {}
func (*R500) readEndpointDataEndpointRequiredRes()  {}
func (*R500) readEndpointDataRes()                  {}
func (*R500) readProviderEndpointProviderRes()      {}
func (*R500) readProviderEndpointRes()              {}
func (*R500) readProviderRegisterDataRes()          {}
func (*R500) updateEndpointDataRes()                {}
func (*R500) updateProviderEndpointRes()            {}
func (*R500) updateProviderRegisterDataRes()        {}

type UpdateEndpointDataReq struct {
	DataName         OptString `json:"dataName"`
	Description      OptString `json:"description"`
	Type             OptString `json:"type"`
	EndpointRequired OptInt    `json:"endpoint_required"`
	EndpointProvided OptInt    `json:"endpoint_provided"`
}

// GetDataName returns the value of DataName.
func (s *UpdateEndpointDataReq) GetDataName() OptString {
	return s.DataName
}

// GetDescription returns the value of Description.
func (s *UpdateEndpointDataReq) GetDescription() OptString {
	return s.Description
}

// GetType returns the value of Type.
func (s *UpdateEndpointDataReq) GetType() OptString {
	return s.Type
}

// GetEndpointRequired returns the value of EndpointRequired.
func (s *UpdateEndpointDataReq) GetEndpointRequired() OptInt {
	return s.EndpointRequired
}

// GetEndpointProvided returns the value of EndpointProvided.
func (s *UpdateEndpointDataReq) GetEndpointProvided() OptInt {
	return s.EndpointProvided
}

// SetDataName sets the value of DataName.
func (s *UpdateEndpointDataReq) SetDataName(val OptString) {
	s.DataName = val
}

// SetDescription sets the value of Description.
func (s *UpdateEndpointDataReq) SetDescription(val OptString) {
	s.Description = val
}

// SetType sets the value of Type.
func (s *UpdateEndpointDataReq) SetType(val OptString) {
	s.Type = val
}

// SetEndpointRequired sets the value of EndpointRequired.
func (s *UpdateEndpointDataReq) SetEndpointRequired(val OptInt) {
	s.EndpointRequired = val
}

// SetEndpointProvided sets the value of EndpointProvided.
func (s *UpdateEndpointDataReq) SetEndpointProvided(val OptInt) {
	s.EndpointProvided = val
}

type UpdateProviderEndpointReq struct {
	Name         OptString `json:"name"`
	Path         OptString `json:"path"`
	Type         OptString `json:"type"`
	Description  OptString `json:"description"`
	RequiredData []int     `json:"required_data"`
	ProvidedData []int     `json:"provided_data"`
	Provider     OptInt    `json:"provider"`
}

// GetName returns the value of Name.
func (s *UpdateProviderEndpointReq) GetName() OptString {
	return s.Name
}

// GetPath returns the value of Path.
func (s *UpdateProviderEndpointReq) GetPath() OptString {
	return s.Path
}

// GetType returns the value of Type.
func (s *UpdateProviderEndpointReq) GetType() OptString {
	return s.Type
}

// GetDescription returns the value of Description.
func (s *UpdateProviderEndpointReq) GetDescription() OptString {
	return s.Description
}

// GetRequiredData returns the value of RequiredData.
func (s *UpdateProviderEndpointReq) GetRequiredData() []int {
	return s.RequiredData
}

// GetProvidedData returns the value of ProvidedData.
func (s *UpdateProviderEndpointReq) GetProvidedData() []int {
	return s.ProvidedData
}

// GetProvider returns the value of Provider.
func (s *UpdateProviderEndpointReq) GetProvider() OptInt {
	return s.Provider
}

// SetName sets the value of Name.
func (s *UpdateProviderEndpointReq) SetName(val OptString) {
	s.Name = val
}

// SetPath sets the value of Path.
func (s *UpdateProviderEndpointReq) SetPath(val OptString) {
	s.Path = val
}

// SetType sets the value of Type.
func (s *UpdateProviderEndpointReq) SetType(val OptString) {
	s.Type = val
}

// SetDescription sets the value of Description.
func (s *UpdateProviderEndpointReq) SetDescription(val OptString) {
	s.Description = val
}

// SetRequiredData sets the value of RequiredData.
func (s *UpdateProviderEndpointReq) SetRequiredData(val []int) {
	s.RequiredData = val
}

// SetProvidedData sets the value of ProvidedData.
func (s *UpdateProviderEndpointReq) SetProvidedData(val []int) {
	s.ProvidedData = val
}

// SetProvider sets the value of Provider.
func (s *UpdateProviderEndpointReq) SetProvider(val OptInt) {
	s.Provider = val
}

type UpdateProviderRegisterDataReq struct {
	Name         OptString `json:"name"`
	Port         OptString `json:"port"`
	Address      OptString `json:"address"`
	Description  OptString `json:"description"`
	LiveInterval OptInt    `json:"liveInterval"`
	LiveTimeout  OptInt    `json:"liveTimeout"`
	Endpoints    []int     `json:"endpoints"`
}

// GetName returns the value of Name.
func (s *UpdateProviderRegisterDataReq) GetName() OptString {
	return s.Name
}

// GetPort returns the value of Port.
func (s *UpdateProviderRegisterDataReq) GetPort() OptString {
	return s.Port
}

// GetAddress returns the value of Address.
func (s *UpdateProviderRegisterDataReq) GetAddress() OptString {
	return s.Address
}

// GetDescription returns the value of Description.
func (s *UpdateProviderRegisterDataReq) GetDescription() OptString {
	return s.Description
}

// GetLiveInterval returns the value of LiveInterval.
func (s *UpdateProviderRegisterDataReq) GetLiveInterval() OptInt {
	return s.LiveInterval
}

// GetLiveTimeout returns the value of LiveTimeout.
func (s *UpdateProviderRegisterDataReq) GetLiveTimeout() OptInt {
	return s.LiveTimeout
}

// GetEndpoints returns the value of Endpoints.
func (s *UpdateProviderRegisterDataReq) GetEndpoints() []int {
	return s.Endpoints
}

// SetName sets the value of Name.
func (s *UpdateProviderRegisterDataReq) SetName(val OptString) {
	s.Name = val
}

// SetPort sets the value of Port.
func (s *UpdateProviderRegisterDataReq) SetPort(val OptString) {
	s.Port = val
}

// SetAddress sets the value of Address.
func (s *UpdateProviderRegisterDataReq) SetAddress(val OptString) {
	s.Address = val
}

// SetDescription sets the value of Description.
func (s *UpdateProviderRegisterDataReq) SetDescription(val OptString) {
	s.Description = val
}

// SetLiveInterval sets the value of LiveInterval.
func (s *UpdateProviderRegisterDataReq) SetLiveInterval(val OptInt) {
	s.LiveInterval = val
}

// SetLiveTimeout sets the value of LiveTimeout.
func (s *UpdateProviderRegisterDataReq) SetLiveTimeout(val OptInt) {
	s.LiveTimeout = val
}

// SetEndpoints sets the value of Endpoints.
func (s *UpdateProviderRegisterDataReq) SetEndpoints(val []int) {
	s.Endpoints = val
}
