// Code generated by ent, DO NOT EDIT.

package providerendpoint

const (
	// Label holds the string label denoting the providerendpoint type in the database.
	Label = "provider_endpoint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// EdgeRequiredData holds the string denoting the required_data edge name in mutations.
	EdgeRequiredData = "required_data"
	// EdgeProvidedData holds the string denoting the provided_data edge name in mutations.
	EdgeProvidedData = "provided_data"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// Table holds the table name of the providerendpoint in the database.
	Table = "provider_endpoints"
	// RequiredDataTable is the table that holds the required_data relation/edge.
	RequiredDataTable = "endpoint_data"
	// RequiredDataInverseTable is the table name for the EndpointData entity.
	// It exists in this package in order to avoid circular dependency with the "endpointdata" package.
	RequiredDataInverseTable = "endpoint_data"
	// RequiredDataColumn is the table column denoting the required_data relation/edge.
	RequiredDataColumn = "provider_endpoint_required_data"
	// ProvidedDataTable is the table that holds the provided_data relation/edge.
	ProvidedDataTable = "endpoint_data"
	// ProvidedDataInverseTable is the table name for the EndpointData entity.
	// It exists in this package in order to avoid circular dependency with the "endpointdata" package.
	ProvidedDataInverseTable = "endpoint_data"
	// ProvidedDataColumn is the table column denoting the provided_data relation/edge.
	ProvidedDataColumn = "provider_endpoint_provided_data"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "provider_endpoints"
	// ProviderInverseTable is the table name for the ProviderRegisterData entity.
	// It exists in this package in order to avoid circular dependency with the "providerregisterdata" package.
	ProviderInverseTable = "provider_register_data"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_register_data_endpoints"
)

// Columns holds all SQL columns for providerendpoint fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPath,
	FieldType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "provider_endpoints"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"provider_register_data_endpoints",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
