// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"servicediscoverer/ent/endpointdata"
	"servicediscoverer/ent/predicate"
	"servicediscoverer/ent/providerendpoint"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EndpointDataQuery is the builder for querying EndpointData entities.
type EndpointDataQuery struct {
	config
	limit                *int
	offset               *int
	unique               *bool
	order                []OrderFunc
	fields               []string
	predicates           []predicate.EndpointData
	withEndpointRequired *ProviderEndpointQuery
	withEndpointProvided *ProviderEndpointQuery
	withFKs              bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EndpointDataQuery builder.
func (edq *EndpointDataQuery) Where(ps ...predicate.EndpointData) *EndpointDataQuery {
	edq.predicates = append(edq.predicates, ps...)
	return edq
}

// Limit adds a limit step to the query.
func (edq *EndpointDataQuery) Limit(limit int) *EndpointDataQuery {
	edq.limit = &limit
	return edq
}

// Offset adds an offset step to the query.
func (edq *EndpointDataQuery) Offset(offset int) *EndpointDataQuery {
	edq.offset = &offset
	return edq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (edq *EndpointDataQuery) Unique(unique bool) *EndpointDataQuery {
	edq.unique = &unique
	return edq
}

// Order adds an order step to the query.
func (edq *EndpointDataQuery) Order(o ...OrderFunc) *EndpointDataQuery {
	edq.order = append(edq.order, o...)
	return edq
}

// QueryEndpointRequired chains the current query on the "endpoint_required" edge.
func (edq *EndpointDataQuery) QueryEndpointRequired() *ProviderEndpointQuery {
	query := &ProviderEndpointQuery{config: edq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := edq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := edq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(endpointdata.Table, endpointdata.FieldID, selector),
			sqlgraph.To(providerendpoint.Table, providerendpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, endpointdata.EndpointRequiredTable, endpointdata.EndpointRequiredColumn),
		)
		fromU = sqlgraph.SetNeighbors(edq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEndpointProvided chains the current query on the "endpoint_provided" edge.
func (edq *EndpointDataQuery) QueryEndpointProvided() *ProviderEndpointQuery {
	query := &ProviderEndpointQuery{config: edq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := edq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := edq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(endpointdata.Table, endpointdata.FieldID, selector),
			sqlgraph.To(providerendpoint.Table, providerendpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, endpointdata.EndpointProvidedTable, endpointdata.EndpointProvidedColumn),
		)
		fromU = sqlgraph.SetNeighbors(edq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EndpointData entity from the query.
// Returns a *NotFoundError when no EndpointData was found.
func (edq *EndpointDataQuery) First(ctx context.Context) (*EndpointData, error) {
	nodes, err := edq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{endpointdata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (edq *EndpointDataQuery) FirstX(ctx context.Context) *EndpointData {
	node, err := edq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EndpointData ID from the query.
// Returns a *NotFoundError when no EndpointData ID was found.
func (edq *EndpointDataQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = edq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{endpointdata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (edq *EndpointDataQuery) FirstIDX(ctx context.Context) int {
	id, err := edq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EndpointData entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EndpointData entity is found.
// Returns a *NotFoundError when no EndpointData entities are found.
func (edq *EndpointDataQuery) Only(ctx context.Context) (*EndpointData, error) {
	nodes, err := edq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{endpointdata.Label}
	default:
		return nil, &NotSingularError{endpointdata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (edq *EndpointDataQuery) OnlyX(ctx context.Context) *EndpointData {
	node, err := edq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EndpointData ID in the query.
// Returns a *NotSingularError when more than one EndpointData ID is found.
// Returns a *NotFoundError when no entities are found.
func (edq *EndpointDataQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = edq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{endpointdata.Label}
	default:
		err = &NotSingularError{endpointdata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (edq *EndpointDataQuery) OnlyIDX(ctx context.Context) int {
	id, err := edq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EndpointDataSlice.
func (edq *EndpointDataQuery) All(ctx context.Context) ([]*EndpointData, error) {
	if err := edq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return edq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (edq *EndpointDataQuery) AllX(ctx context.Context) []*EndpointData {
	nodes, err := edq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EndpointData IDs.
func (edq *EndpointDataQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := edq.Select(endpointdata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (edq *EndpointDataQuery) IDsX(ctx context.Context) []int {
	ids, err := edq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (edq *EndpointDataQuery) Count(ctx context.Context) (int, error) {
	if err := edq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return edq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (edq *EndpointDataQuery) CountX(ctx context.Context) int {
	count, err := edq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (edq *EndpointDataQuery) Exist(ctx context.Context) (bool, error) {
	if err := edq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return edq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (edq *EndpointDataQuery) ExistX(ctx context.Context) bool {
	exist, err := edq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EndpointDataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (edq *EndpointDataQuery) Clone() *EndpointDataQuery {
	if edq == nil {
		return nil
	}
	return &EndpointDataQuery{
		config:               edq.config,
		limit:                edq.limit,
		offset:               edq.offset,
		order:                append([]OrderFunc{}, edq.order...),
		predicates:           append([]predicate.EndpointData{}, edq.predicates...),
		withEndpointRequired: edq.withEndpointRequired.Clone(),
		withEndpointProvided: edq.withEndpointProvided.Clone(),
		// clone intermediate query.
		sql:    edq.sql.Clone(),
		path:   edq.path,
		unique: edq.unique,
	}
}

// WithEndpointRequired tells the query-builder to eager-load the nodes that are connected to
// the "endpoint_required" edge. The optional arguments are used to configure the query builder of the edge.
func (edq *EndpointDataQuery) WithEndpointRequired(opts ...func(*ProviderEndpointQuery)) *EndpointDataQuery {
	query := &ProviderEndpointQuery{config: edq.config}
	for _, opt := range opts {
		opt(query)
	}
	edq.withEndpointRequired = query
	return edq
}

// WithEndpointProvided tells the query-builder to eager-load the nodes that are connected to
// the "endpoint_provided" edge. The optional arguments are used to configure the query builder of the edge.
func (edq *EndpointDataQuery) WithEndpointProvided(opts ...func(*ProviderEndpointQuery)) *EndpointDataQuery {
	query := &ProviderEndpointQuery{config: edq.config}
	for _, opt := range opts {
		opt(query)
	}
	edq.withEndpointProvided = query
	return edq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DataName string `json:"dataName,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EndpointData.Query().
//		GroupBy(endpointdata.FieldDataName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (edq *EndpointDataQuery) GroupBy(field string, fields ...string) *EndpointDataGroupBy {
	grbuild := &EndpointDataGroupBy{config: edq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := edq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return edq.sqlQuery(ctx), nil
	}
	grbuild.label = endpointdata.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DataName string `json:"dataName,omitempty"`
//	}
//
//	client.EndpointData.Query().
//		Select(endpointdata.FieldDataName).
//		Scan(ctx, &v)
func (edq *EndpointDataQuery) Select(fields ...string) *EndpointDataSelect {
	edq.fields = append(edq.fields, fields...)
	selbuild := &EndpointDataSelect{EndpointDataQuery: edq}
	selbuild.label = endpointdata.Label
	selbuild.flds, selbuild.scan = &edq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a EndpointDataSelect configured with the given aggregations.
func (edq *EndpointDataQuery) Aggregate(fns ...AggregateFunc) *EndpointDataSelect {
	return edq.Select().Aggregate(fns...)
}

func (edq *EndpointDataQuery) prepareQuery(ctx context.Context) error {
	for _, f := range edq.fields {
		if !endpointdata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if edq.path != nil {
		prev, err := edq.path(ctx)
		if err != nil {
			return err
		}
		edq.sql = prev
	}
	return nil
}

func (edq *EndpointDataQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EndpointData, error) {
	var (
		nodes       = []*EndpointData{}
		withFKs     = edq.withFKs
		_spec       = edq.querySpec()
		loadedTypes = [2]bool{
			edq.withEndpointRequired != nil,
			edq.withEndpointProvided != nil,
		}
	)
	if edq.withEndpointRequired != nil || edq.withEndpointProvided != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, endpointdata.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EndpointData).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EndpointData{config: edq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, edq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := edq.withEndpointRequired; query != nil {
		if err := edq.loadEndpointRequired(ctx, query, nodes, nil,
			func(n *EndpointData, e *ProviderEndpoint) { n.Edges.EndpointRequired = e }); err != nil {
			return nil, err
		}
	}
	if query := edq.withEndpointProvided; query != nil {
		if err := edq.loadEndpointProvided(ctx, query, nodes, nil,
			func(n *EndpointData, e *ProviderEndpoint) { n.Edges.EndpointProvided = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (edq *EndpointDataQuery) loadEndpointRequired(ctx context.Context, query *ProviderEndpointQuery, nodes []*EndpointData, init func(*EndpointData), assign func(*EndpointData, *ProviderEndpoint)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EndpointData)
	for i := range nodes {
		if nodes[i].provider_endpoint_required_data == nil {
			continue
		}
		fk := *nodes[i].provider_endpoint_required_data
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(providerendpoint.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_endpoint_required_data" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (edq *EndpointDataQuery) loadEndpointProvided(ctx context.Context, query *ProviderEndpointQuery, nodes []*EndpointData, init func(*EndpointData), assign func(*EndpointData, *ProviderEndpoint)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EndpointData)
	for i := range nodes {
		if nodes[i].provider_endpoint_provided_data == nil {
			continue
		}
		fk := *nodes[i].provider_endpoint_provided_data
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(providerendpoint.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_endpoint_provided_data" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (edq *EndpointDataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := edq.querySpec()
	_spec.Node.Columns = edq.fields
	if len(edq.fields) > 0 {
		_spec.Unique = edq.unique != nil && *edq.unique
	}
	return sqlgraph.CountNodes(ctx, edq.driver, _spec)
}

func (edq *EndpointDataQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := edq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (edq *EndpointDataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   endpointdata.Table,
			Columns: endpointdata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: endpointdata.FieldID,
			},
		},
		From:   edq.sql,
		Unique: true,
	}
	if unique := edq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := edq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, endpointdata.FieldID)
		for i := range fields {
			if fields[i] != endpointdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := edq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := edq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := edq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := edq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (edq *EndpointDataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(edq.driver.Dialect())
	t1 := builder.Table(endpointdata.Table)
	columns := edq.fields
	if len(columns) == 0 {
		columns = endpointdata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if edq.sql != nil {
		selector = edq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if edq.unique != nil && *edq.unique {
		selector.Distinct()
	}
	for _, p := range edq.predicates {
		p(selector)
	}
	for _, p := range edq.order {
		p(selector)
	}
	if offset := edq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := edq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EndpointDataGroupBy is the group-by builder for EndpointData entities.
type EndpointDataGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (edgb *EndpointDataGroupBy) Aggregate(fns ...AggregateFunc) *EndpointDataGroupBy {
	edgb.fns = append(edgb.fns, fns...)
	return edgb
}

// Scan applies the group-by query and scans the result into the given value.
func (edgb *EndpointDataGroupBy) Scan(ctx context.Context, v any) error {
	query, err := edgb.path(ctx)
	if err != nil {
		return err
	}
	edgb.sql = query
	return edgb.sqlScan(ctx, v)
}

func (edgb *EndpointDataGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range edgb.fields {
		if !endpointdata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := edgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := edgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (edgb *EndpointDataGroupBy) sqlQuery() *sql.Selector {
	selector := edgb.sql.Select()
	aggregation := make([]string, 0, len(edgb.fns))
	for _, fn := range edgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(edgb.fields)+len(edgb.fns))
		for _, f := range edgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(edgb.fields...)...)
}

// EndpointDataSelect is the builder for selecting fields of EndpointData entities.
type EndpointDataSelect struct {
	*EndpointDataQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eds *EndpointDataSelect) Aggregate(fns ...AggregateFunc) *EndpointDataSelect {
	eds.fns = append(eds.fns, fns...)
	return eds
}

// Scan applies the selector query and scans the result into the given value.
func (eds *EndpointDataSelect) Scan(ctx context.Context, v any) error {
	if err := eds.prepareQuery(ctx); err != nil {
		return err
	}
	eds.sql = eds.EndpointDataQuery.sqlQuery(ctx)
	return eds.sqlScan(ctx, v)
}

func (eds *EndpointDataSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(eds.fns))
	for _, fn := range eds.fns {
		aggregation = append(aggregation, fn(eds.sql))
	}
	switch n := len(*eds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		eds.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		eds.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := eds.sql.Query()
	if err := eds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
