// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"servicediscoverer/ent/endpointdata"
	"servicediscoverer/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EndpointDataDelete is the builder for deleting a EndpointData entity.
type EndpointDataDelete struct {
	config
	hooks    []Hook
	mutation *EndpointDataMutation
}

// Where appends a list predicates to the EndpointDataDelete builder.
func (edd *EndpointDataDelete) Where(ps ...predicate.EndpointData) *EndpointDataDelete {
	edd.mutation.Where(ps...)
	return edd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (edd *EndpointDataDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(edd.hooks) == 0 {
		affected, err = edd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EndpointDataMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			edd.mutation = mutation
			affected, err = edd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(edd.hooks) - 1; i >= 0; i-- {
			if edd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = edd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, edd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (edd *EndpointDataDelete) ExecX(ctx context.Context) int {
	n, err := edd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (edd *EndpointDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: endpointdata.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: endpointdata.FieldID,
			},
		},
	}
	if ps := edd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, edd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// EndpointDataDeleteOne is the builder for deleting a single EndpointData entity.
type EndpointDataDeleteOne struct {
	edd *EndpointDataDelete
}

// Exec executes the deletion query.
func (eddo *EndpointDataDeleteOne) Exec(ctx context.Context) error {
	n, err := eddo.edd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{endpointdata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eddo *EndpointDataDeleteOne) ExecX(ctx context.Context) {
	eddo.edd.ExecX(ctx)
}
