// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"servicediscoverer/ent/predicate"
	"servicediscoverer/ent/providerendpoint"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderEndpointDelete is the builder for deleting a ProviderEndpoint entity.
type ProviderEndpointDelete struct {
	config
	hooks    []Hook
	mutation *ProviderEndpointMutation
}

// Where appends a list predicates to the ProviderEndpointDelete builder.
func (ped *ProviderEndpointDelete) Where(ps ...predicate.ProviderEndpoint) *ProviderEndpointDelete {
	ped.mutation.Where(ps...)
	return ped
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ped *ProviderEndpointDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ProviderEndpointMutation](ctx, ped.sqlExec, ped.mutation, ped.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ped *ProviderEndpointDelete) ExecX(ctx context.Context) int {
	n, err := ped.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ped *ProviderEndpointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: providerendpoint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: providerendpoint.FieldID,
			},
		},
	}
	if ps := ped.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ped.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ped.mutation.done = true
	return affected, err
}

// ProviderEndpointDeleteOne is the builder for deleting a single ProviderEndpoint entity.
type ProviderEndpointDeleteOne struct {
	ped *ProviderEndpointDelete
}

// Exec executes the deletion query.
func (pedo *ProviderEndpointDeleteOne) Exec(ctx context.Context) error {
	n, err := pedo.ped.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{providerendpoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pedo *ProviderEndpointDeleteOne) ExecX(ctx context.Context) {
	pedo.ped.ExecX(ctx)
}
