// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EndpointData is the predicate function for endpointdata builders.
type EndpointData func(*sql.Selector)

// ProviderEndpoint is the predicate function for providerendpoint builders.
type ProviderEndpoint func(*sql.Selector)

// ProviderRegisterData is the predicate function for providerregisterdata builders.
type ProviderRegisterData func(*sql.Selector)
